# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hNq1MsDkj6VElDS9_ZWQ9ViJgAEjeUS
"""

import streamlit as st
import joblib
import numpy as np

model = joblib.load('model_jantung_fix.sav')

st.title("Aplikasi Prediksi Penyakit Jantung 🫀")
st.write("Masukkan data pasien untuk melihat prediksi diagnosa.")

col1, col2 = st.columns(2)

with col1:
    age = st.number_input("Umur", min_value=1, max_value=120, value=50)
    sex = st.selectbox("Jenis Kelamin", [0, 1], format_func=lambda x: "Perempuan" if x == 0 else "Laki-laki")
    cp = st.selectbox("Tipe Nyeri Dada (CP)", [0, 1, 2, 3])
    trestbps = st.number_input("Tekanan Darah (mm Hg)", value=120)
    chol = st.number_input("Kolesterol (mg/dl)", value=200)
    fbs = st.selectbox("Gula Darah Puasa > 120 mg/dl", [0, 1], format_func=lambda x: "False" if x == 0 else "True")
    restecg = st.selectbox("Hasil EKG Istirahat", [0, 1, 2])

with col2:
    thalach = st.number_input("Detak Jantung Maksimum", value=150)
    exang = st.selectbox("Nyeri Dada akibat Olahraga", [0, 1], format_func=lambda x: "Tidak" if x == 0 else "Ya")
    oldpeak = st.number_input("ST Depression", value=1.0)
    slope = st.selectbox("Slope ST Segment", [0, 1, 2])
    ca = st.selectbox("Jumlah Pembuluh Utama (0-3)", [0, 1, 2, 3])
    thal = st.selectbox("Thalassemia", [0, 1, 2, 3])

if st.button("Prediksi Hasil"):
    input_data = np.array([[age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal]])

    prediction = model.predict(input_data)
    probabilitas = model.predict_proba(input_data)

    st.subheader("Hasil Diagnosa:")
    if prediction[0] == 1:
        st.error(f"⚠️ Pasien DIPREDIKSI MENGIDAP Penyakit Jantung (Probabilitas: {probabilitas[0][1]*100:.2f}%)")
    else:
        st.success(f"✅ Pasien DIPREDIKSI SEHAT (Probabilitas: {probabilitas[0][0]*100:.2f}%)")