# -*- coding: utf-8 -*-
"""app1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8g7HOJdpEovPVg_zpwvnRP1fvBVgndZ
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np

saved_data = joblib.load('model_jantung_fix.sav')
model = saved_data['model']
encoders = saved_data['encoders']
num_imputer = saved_data['num_imputer']
cat_imputer = saved_data['cat_imputer']

st.set_page_config(page_title="Prediksi Jantung", layout="centered")

st.title("🫀 Prediksi Risiko Penyakit Jantung")
st.write("Masukkan data klinis pasien di bawah ini (Dataset UCI Heart Disease Combined):")

user_input = {}

col1, col2 = st.columns(2)

with col1:
    user_input['age'] = st.number_input("Usia (Tahun)", min_value=1, max_value=100, value=50)

    # Opsi sesuai data asli di CSV (Huruf besar/kecil harus sama persis dengan opsi di encoders)
    sex_opts = encoders['sex'].classes_
    sex_val = st.selectbox("Jenis Kelamin", sex_opts)
    user_input['sex'] = sex_val

    cp_opts = encoders['cp'].classes_
    cp_val = st.selectbox("Tipe Nyeri Dada (Chest Pain)", cp_opts)
    user_input['cp'] = cp_val

    user_input['trestbps'] = st.number_input("Tekanan Darah (mm Hg)", value=120)
    user_input['chol'] = st.number_input("Kolesterol (mg/dl)", value=200)

    fbs_opts = encoders['fbs'].classes_
    fbs_val = st.selectbox("Gula Darah Puasa > 120 mg/dl?", fbs_opts)
    user_input['fbs'] = fbs_val

    restecg_opts = encoders['restecg'].classes_
    restecg_val = st.selectbox("Hasil EKG Istirahat", restecg_opts)
    user_input['restecg'] = restecg_val

with col2:
    user_input['thalch'] = st.number_input("Detak Jantung Maksimum", value=150)

    exang_opts = encoders['exang'].classes_
    exang_val = st.selectbox("Nyeri Dada saat Olahraga?", exang_opts)
    user_input['exang'] = exang_val

    user_input['oldpeak'] = st.number_input("ST Depression (Oldpeak)", value=0.0)

    slope_opts = encoders['slope'].classes_
    slope_val = st.selectbox("Slope ST Segment", slope_opts)
    user_input['slope'] = slope_val

    # ca adalah float di data asli, tapi inputnya integer jumlah pembuluh
    user_input['ca'] = st.number_input("Jumlah Pembuluh Utama (CA) (0-3)", min_value=0.0, max_value=4.0, value=0.0, step=1.0)

    thal_opts = encoders['thal'].classes_
    thal_val = st.selectbox("Thalassemia", thal_opts)
    user_input['thal'] = thal_val

if st.button("Analisis Risiko"):
    input_df = pd.DataFrame([user_input])

    cat_cols = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'thal']
    num_cols = ['age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca']

    for col in cat_cols:
        input_df[col] = encoders[col].transform([input_df[col][0]])

    final_cols = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
    input_data = input_df[final_cols]

    prediction = model.predict(input_data)
    prob = model.predict_proba(input_data)

    st.divider()

    if prediction[0] == 1:
        st.error(f"### ⚠️ Hasil: Berisiko Penyakit Jantung")
        st.write(f"Tingkat Kepercayaan Model: **{prob[0][1]*100:.1f}%**")
        st.warning("Saran: Segera konsultasikan dengan dokter kardiologi untuk pemeriksaan lebih lanjut.")
    else:
        st.success(f"### ✅ Hasil: Jantung Sehat")
        st.write(f"Tingkat Kepercayaan Model: **{prob[0][0]*100:.1f}%**")
        st.info("Tetap jaga pola makan dan olahraga teratur.")